# Generated by Django 5.2 on 2025-09-16 14:31

import django.utils.timezone
from django.db import migrations, models
from django.core.serializers.json import DjangoJSONEncoder


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_used',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_miles',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='client_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='payload',
            field=models.JSONField(default=dict, blank=True, encoder=DjangoJSONEncoder),
            preserve_default=True,
        ),
    ]
