# Generated by Django 5.2 on 2025-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_options_rename_timestamp_trip_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='log_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
