# Generated by Django 5.2.6 on 2025-09-16 15:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_dailylog_log_data_alter_trip_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
